spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringBoot
    username: postgres
    password: sk143
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
