# ===============================
# 🔹 Spring Boot Application Name
# ===============================
spring:
  application:
    name: 2FA

  # ===============================
  # 🔹 Database Configuration (PostgreSQL)
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringBoot
    username: postgres
    password: sk143
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  # ===============================
  # 🔹 Hibernate / JPA Settings
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true